# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /group/techsup/parkerh/ext_axi_interface/ext_axi_interface.srcs/sources_1/ip/axi_gpio_0/axi_gpio_0.xci
# IP: The module: 'axi_gpio_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /group/techsup/parkerh/ext_axi_interface/ext_axi_interface.srcs/sources_1/ip/axi_gpio_0/axi_gpio_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /group/techsup/parkerh/ext_axi_interface/ext_axi_interface.srcs/sources_1/ip/axi_gpio_0/axi_gpio_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /group/techsup/parkerh/ext_axi_interface/ext_axi_interface.srcs/sources_1/ip/axi_gpio_0/axi_gpio_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /group/techsup/parkerh/ext_axi_interface/ext_axi_interface.srcs/sources_1/ip/axi_gpio_0/axi_gpio_0.xci
# IP: The module: 'axi_gpio_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /group/techsup/parkerh/ext_axi_interface/ext_axi_interface.srcs/sources_1/ip/axi_gpio_0/axi_gpio_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /group/techsup/parkerh/ext_axi_interface/ext_axi_interface.srcs/sources_1/ip/axi_gpio_0/axi_gpio_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /group/techsup/parkerh/ext_axi_interface/ext_axi_interface.srcs/sources_1/ip/axi_gpio_0/axi_gpio_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
